questionnaire_admin:
    resource: "@QuestionnaireAdminBundle/Resources/config/routing.yml"
    prefix:   /

questionnaire:
    resource: "@QuestionnaireBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
