security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        default:
            pattern:    ^/
            anonymous: ~
            provider: our_db_provider
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            anonymous: ~
