questionnaire_homepage:
    path:     /
    defaults: { _controller: QuestionnaireBundle:Index:index }

login:
    path:     /login
    defaults: { _controller: QuestionnaireBundle:Login:index }

registration:
    path:     /registration
    defaults: { _controller: QuestionnaireBundle:Registration:index }

registration_register:
    path:     /registration/register
    defaults: { _controller: QuestionnaireBundle:Registration:register }

question_get:
    path:     /question/get/{questionnaireId}
    defaults: { _controller: QuestionnaireBundle:Question:get }