questionnaire_homepage:
    path:     /hello/{name}
    defaults: { _controller: QuestionnaireBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: QuestionnaireBundle:Login:index }

registration:
    path:     /registration
    defaults: { _controller: QuestionnaireBundle:Registration:index }

question:
    path:     /question
    defaults: { _controller: QuestionnaireBundle:Question:index }