admin_home:
    path:     /admin
    defaults: { _controller: QuestionnaireBundle:Admin:index }

questionnaire_homepage:
    path:     /
    defaults: { _controller: QuestionnaireBundle:Index:index }

login:
    path:     /login
    defaults: { _controller: QuestionnaireBundle:Login:index }

registration:
    path:     /registration
    defaults: { _controller: QuestionnaireBundle:Registration:index }

registration_register:
    path:     /registration/register
    defaults: { _controller: QuestionnaireBundle:Registration:register }

registration_submit:
    path:     /registration/submitRegistration
    defaults: { _controller: QuestionnaireBundle:Registration:submitRegistration }

questionnaires_get:
    path:     /questionnaires/get
    defaults: { _controller: QuestionnaireBundle:Questionnaires:get }

questionnaires_submit:
    path:     /questionnaires/submitQuestionnaire/{id}
    defaults: { _controller: QuestionnaireBundle:Questionnaires:submitQuestionnaire }

questionnaire_create:
    path:     /questionnaire/create
    defaults: { _controller: QuestionnaireBundle:Questionnaire:create }

questionnaire_categories_get:
    path:     /questionnaire_categories/get
    defaults: { _controller: QuestionnaireBundle:QuestionnaireCategories:get}

questions_get:
    path:     /questions/get/{questionnaireId}
    defaults: { _controller: QuestionnaireBundle:Questions:get }

question_get:
    path:     /question/get/{questionId}
    defaults: { _controller: QuestionnaireBundle:Question:get }

landing_page:
    path:     /home
    defaults: { _controller: QuestionnaireBundle:Home:index }

question_submit:
    path:     /question/submitAnswer
    defaults: { _controller: QuestionnaireBundle:Question:submitAnswer }

question_submit_multi:
    path:     /question/submitMultiAnswer
    defaults: { _controller: QuestionnaireBundle:Question:submitMultiAnswer }

question_create:
    path:     /question/create
    defaults: { _controller: QuestionnaireBundle:Question:create }