questionnaire_homepage:
    path:     /
    defaults: { _controller: QuestionnaireBundle:Index:index }

login:
    path:     /login
    defaults: { _controller: QuestionnaireBundle:Login:index }

registration:
    path:     /registration
    defaults: { _controller: QuestionnaireBundle:Registration:index }

registration_register:
    path:     /registration/register
    defaults: { _controller: QuestionnaireBundle:Registration:register }

question_get:
    path:     /question/get/{questionId}
    defaults: { _controller: QuestionnaireBundle:Question:get }

question_get_tree:
    path:     /question/getTree
    defaults: { _controller: QuestionnaireBundle:Question:getTree }

questionnaire_get:
    path:     /question/getQuestionnaire/{questionnaireId}
    defaults: { _controller: QuestionnaireBundle:Question:getQuestionnaire }

questionnaires_get:
    path:     /questionnaire/getQuestionnaires
    defaults: { _controller: QuestionnaireBundle:Questionnaire:getQuestionnaires }

admin_home:
    path:     /admin
    defaults: { _controller: QuestionnaireBundle:Admin:index }

question_submit:
    path:     /question/submitAnswer
    defaults: { _controller: QuestionnaireBundle:Question:submitAnswer }

question_create:
    path:     /question/create
    defaults: { _controller: QuestionnaireBundle:Question:create }