services:
#    questionnaire.example:
#        class: QuestionnaireBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    questionnaire.dataExporter:
        class: QuestionnaireBundle\Service\JsonExporter
        arguments: [doctrine.orm.entity_manager]
